print("------")
print("Pyton has entered the building.")
print("Let the party start!")
print("I am making another changes")
print("I am ensuring if I can upload it right this time")
print("-------")